# fly.toml app configuration file generated for teabags-runner on 2024-02-17T21:15:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '<app_name>'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[[mounts]]
  source = '<app_name>_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
